spring.application.name=person_ms

spring.r2dbc.url=r2dbc:mysql://localhost:3306/person
spring.r2dbc.username=root
spring.r2dbc.password=admin

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

adapters.bootcamp-ms.url=http://localhost:8082

server.port=8083